// Generated by gencpp from file bfsdriver_1_1/ImageStamp.msg
// DO NOT EDIT!


#ifndef BFSDRIVER_1_1_MESSAGE_IMAGESTAMP_H
#define BFSDRIVER_1_1_MESSAGE_IMAGESTAMP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace bfsdriver_1_1
{
template <class ContainerAllocator>
struct ImageStamp_
{
  typedef ImageStamp_<ContainerAllocator> Type;

  ImageStamp_()
    : img()
    , timestamp(0)  {
    }
  ImageStamp_(const ContainerAllocator& _alloc)
    : img(_alloc)
    , timestamp(0)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _img_type;
  _img_type img;

   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;





  typedef boost::shared_ptr< ::bfsdriver_1_1::ImageStamp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bfsdriver_1_1::ImageStamp_<ContainerAllocator> const> ConstPtr;

}; // struct ImageStamp_

typedef ::bfsdriver_1_1::ImageStamp_<std::allocator<void> > ImageStamp;

typedef boost::shared_ptr< ::bfsdriver_1_1::ImageStamp > ImageStampPtr;
typedef boost::shared_ptr< ::bfsdriver_1_1::ImageStamp const> ImageStampConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bfsdriver_1_1::ImageStamp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bfsdriver_1_1::ImageStamp_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bfsdriver_1_1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'bfsdriver_1_1': ['/root/aws/camera_driver_yucong/src/bfsdriver_1_1/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bfsdriver_1_1::ImageStamp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bfsdriver_1_1::ImageStamp_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bfsdriver_1_1::ImageStamp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bfsdriver_1_1::ImageStamp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bfsdriver_1_1::ImageStamp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bfsdriver_1_1::ImageStamp_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bfsdriver_1_1::ImageStamp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a883a9426baf2a438022495173b1e3df";
  }

  static const char* value(const ::bfsdriver_1_1::ImageStamp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa883a9426baf2a43ULL;
  static const uint64_t static_value2 = 0x8022495173b1e3dfULL;
};

template<class ContainerAllocator>
struct DataType< ::bfsdriver_1_1::ImageStamp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bfsdriver_1_1/ImageStamp";
  }

  static const char* value(const ::bfsdriver_1_1::ImageStamp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bfsdriver_1_1::ImageStamp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/Image img\n\
uint64 timestamp\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::bfsdriver_1_1::ImageStamp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bfsdriver_1_1::ImageStamp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.img);
      stream.next(m.timestamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageStamp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bfsdriver_1_1::ImageStamp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bfsdriver_1_1::ImageStamp_<ContainerAllocator>& v)
  {
    s << indent << "img: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.img);
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BFSDRIVER_1_1_MESSAGE_IMAGESTAMP_H
